<a href="https://colab.research.google.com/github/chandankr2878/chandan-colab/blob/main/pa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data={
    "name":["chandan","vicky","arun","sunny","harshit"],
    "age":[22,23,24,25,26],
    "salary":[100000,90000,80000,70000,60000]

}
df=pd.DataFrame(data)
print(df)

      name  age  salary
0  chandan   22  100000
1    vicky   23   90000
2     arun   24   80000
3    sunny   25   70000
4  harshit   26   60000

In [13]:
import pandas as pd
data={
    "name":["chandan","vicky","arun","sunny","harshit"],
    "age":[22,23,24,25,26],
    "salary":[100000,90000,80000,70000,60000]

}
df=pd.DataFrame(data)
print(df[(df['age']>24) & (df["salary"]==70000)])
# print(df)

    name  age  salary
3  sunny   25   70000

In [17]:
import pandas as pd
data={
    "name":["chandan","vicky","arun","sunny","harshit"],
    "age":[22,23,24,25,26],
    "salary":[100000,90000,80000,70000,60000]

}
df=pd.DataFrame(data)
print(df.where(df["age"]==23,other="not good"))

       name       age    salary
0  not good  not good  not good
1     vicky        23     90000
2  not good  not good  not good
3  not good  not good  not good
4  not good  not good  not good

row and column

In [24]:
#add new column
import pandas as pd
data={
    "name":["chandan","vicky","arun","sunny","harshit"],
    "age":[22,23,24,25,26],
    "salary":[100000,90000,80000,70000,60000]

}
df=pd.DataFrame(data)
df["team"]=["ceo","hr","cto","da","dev"]
df["bonus"]=df["salary"]*3# by multi
df

      name  age  salary team   bonus
0  chandan   22  100000  ceo  300000
1    vicky   23   90000   hr  270000
2     arun   24   80000  cto  240000
3    sunny   25   70000   da  210000
4  harshit   26   60000  dev  180000

In [61]:
# add row
import pandas as pd
data={
    "name":["chandan","vicky","arun","sunny","harshit"],
    "age":[22,23,24,25,26],
    "salary":[100000,90000,98000,70000,75000]

}
df=pd.DataFrame(data)
# df.loc[len(df)]=["sam",27,1000000]
# print(len(df))
# print(df)

# df.loc[1,"salary"]=98000
# print(df)
# df.loc[df.name=="arun","salary"]=78000
# print(df)
df.drop(df[df.name=="sam"].index,inplace=True)# drop delete row
df
print(df)
df["bonus"]=df["salary"]
df
df.drop("bonus",axis=1,inplace=True)
df
df.sort_values("salary",ascending=True)
df

      name  age  salary
0  chandan   22  100000
1    vicky   23   90000
2     arun   24   98000
3    sunny   25   70000
4  harshit   26   75000

      name  age  salary
0  chandan   22  100000
1    vicky   23   90000
2     arun   24   98000
3    sunny   25   70000
4  harshit   26   75000

#date value formating